name: Release

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - "README.md"
      - "**/*.README.md"
      - "**/*.env.example"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/my-coding-journey-server
            git pull origin main
            yarn install
            pm2 restart mcj-server
